### ISSUE TITLE
请问大佬，为什么使用CPU可以正常跑，使用CUDA就报错unsupported conv activation mode "LeakyRelu"

### ISSUE THREAD

**Issue by baishouwujianfei** [season-studio/MeloTTS-ONNX#5]
> Traceback (most recent call last):
  File "F:\project\voice\MeloTTS-ONNX\33.py", line 3, in <module>
    tc = OpenVoiceToneClone_ONNX("./openvoice_tone_clone_onnx", execution_provider="CUDA", verbose=True)
  File "F:\project\voice\MeloTTS-ONNX\melo_onnx\main.py", line 266, in __init__
    self.__tc_infer = self.create_onnx_infer(tc_infer_factor, os.path.join(model_path, "tone_clone_model.onnx"), self.__execution_providers, onnx_session_options, onnx_params)
  File "F:\project\voice\MeloTTS-ONNX\melo_onnx\main.py", line 17, in create_onnx_infer
    session = ort.InferenceSession(onnx_model_path, sess_options=BaseClassForOnnxInfer.adjust_onnx_session_options(session_options), providers=providers, **(onnx_params or {}))
  File "F:\miniconda\envs\melo\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 465, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\miniconda\envs\melo\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 537, in _create_inference_session        
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\contrib_ops\cuda\fused_conv.cc:68 onnxruntime::contrib::cuda::FusedConv<float>::FusedConv [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"

详细报错如上

**Comment by hajkeoadf** [comment]
同问

**Comment by Jiayun-Zhang** [comment]
同问
